- judges/quality-of-service/quality-of-service.rb
- judges/quality-of-service/simple-collect.yml
Merge this PR [fbe#48](https://github.com/zerocracy/fbe/pull/48) before
> #156: implement calculate rejection pull request rate for repos

- judges/label-was-attached/label-was-attached.rb
- test/judges/test-label-was-attached.rb
* Added removing the issue when the GitHub API returns a 404 status
* Added tests
Fixes #218
> #218 delete lost issues when we can't find them

- judges/quality-of-service/quality-of-service.rb
- test/judges/test-quality-of-service.rb
* Substitute `0` if `Fbe.octo.workflow_run_usage(repo, json[:id])[:run_duration_ms]` is `nil`
* Added test
Fixes #261
> #261 `NoMethodError` in `quality-of-service.rb`

- judges/quality-of-service/quality-of-service.rb
- judges/quality-of-service/simple-collect.yml
- test/judges/test-quality-of-service.rb
@yegor256 Merge https://github.com/zerocracy/fbe/pull/70 PR before
> #188: implement calculate average hoc and number of files changed in recent merged PRs

- judges/github-events/github-events.rb
- test/judges/test-github-events.rb
- test/test__helper.rb
@yegor256 merge https://github.com/zerocracy/fbe/pull/77 PR before
Closes #214
> #214 new attributes `failed_builds` and `succeeded_builds` for `pull-was-merged`

- Gemfile.lock
- judges/github-events/github-events.rb
- test/judges/test-github-events.rb
`pr[:base][:login]` is nil. this was a typo.
Related to https://github.com/zerocracy/fbe/issues/78
> use correct attributes of the pull request hash

- Gemfile.lock
- judges/github-events/github-events.rb
- judges/github-events/scan-many-repos.yml
- test/judges/test-github-events.rb
require merging this pr https://github.com/zerocracy/fbe/pull/82 before
Fixes #311
> #311 fix "workflow not found" error

- judges/quality-of-service/quality-of-service.rb
- test/judges/test-quality-of-service.rb
> #189 add `average_build_mttr` into QoS

- judges/quality-of-service/quality-of-service.rb
- judges/quality-of-service/simple-collect.yml
- test/judges/test-quality-of-service.rb
Closes #191 
Fail, because need merge https://github.com/zerocracy/fbe/pull/93 first
> #191: calculate average review comments size for pr

- judges/quality-of-service/quality-of-service.rb
- test/judges/test-quality-of-service.rb
> #338: fix review times in QoS

- Gemfile.lock
- judges/github-events/github-events.rb
A field `pr[:base][:repo][:owner]` is not stable, sometimes I don't see it, for example an event with id `42193949105` (https://api.github.com/repos/zerocracy/judges-action/events)
I suggest using `full_name`, splitting it by `/` and using the first value.
Removed `owner` from the test data: https://github.com/zerocracy/fbe/pull/102
fixes #350
> #350 NoMethodError: undefined method `[]` for nil

- Gemfile.lock
- judges/dimensions-of-terrain/dimensions-of-terrain.rb
- test/judges/test-dimensions-of-terrain.rb
> #200: calculate total number of issues and pull requests

- judges/dimensions-of-terrain/dimensions-of-terrain.rb
- judges/dimensions-of-terrain/measure-all.yml
- test/judges/test-dimensions-of-terrain.rb
> #238: calculate total number of unique active contributors

- judges/dimensions-of-terrain/dimensions-of-terrain.rb
- test/judges/test-dimensions-of-terrain.rb
> #239: ignore archived repos when count `total_repositories` in DoT

- Gemfile.lock
- judges/dimensions-of-terrain/dimensions-of-terrain.rb
- test/judges/test-dimensions-of-terrain.rb
> #380: add check for empty repositories in DoT

- Makefile
- README.md
- action.yml
- entry.sh
> #345: make popular options transmission directly to YAML configuration

- judges/github-events/github-events.rb
- test/judges/test-github-events.rb
> #397: fix get actual repo name in github events

- judges/eliminate-ghosts/eliminate-ghosts.rb
- judges/eliminate-ghosts/scan-users.yml
- test/judges/test-eliminate-ghosts.rb
Test fail, because this https://github.com/zerocracy/fbe/pull/174 PR need merge before
Closes #544
> #544: add eliminate-ghosts judge that delete `who` property when GitHub user is gone

- judges/erase-repository/erase-repository.rb
- judges/erase-repository/scan_repos.yml
- test/judges/test-erase-repository.rb
Test fail, because this https://github.com/zerocracy/fbe/pull/177 PR need merge before
Closes #545
> #545: add erase-repository judge that delete `repository` property when GitHub repository is gone

- judges/github-events/github-events.rb
- test/judges/test-github-events.rb
> #601: handle 403 error in github-events
