judges/github-events/github-events.rb, test/judges/test-github-events.rb
I added a test with similar JSON data that arrives to us.
There, I added two events similar to our problem
In `github-events.rb`, when the event is `PullRequestReviewEvent`, I added a check to see if the user is a reviewer or not.
=> #209 `pull-was-reviewed` is coming for the person who didn't do the review

judges/label-was-attached/label-was-attached.rb, test/judges/test-label-was-attached.rb
* Added catching of `Octokit::NotFound` exception
* Updated tests
Fixes #229
=> #229 delete lost issues

judges/quality-of-service/quality-of-service.rb, judges/quality-of-service/simple-collect.yml
@yegor256 Merge this PR [fbe#53](https://github.com/zerocracy/fbe/pull/53) before
=> #155: implement calculate average build duration

Dockerfile, entry.sh
I'm not sure about my bash skills, but it might look something like this
=> #224: add suffix action_version meta if there is a mismatch with the latest on GitHub

test/judges/test-quality-of-service.rb, test/test__helper.rb
Added stub for `Time.now`
Fixes #271
=> #271 calculate the date in the tests

judges/quantity-of-deliverables/quantity-of-deliverables.rb, test/judges/test-quantity-of-deliverables.rb
* Added skipping repo if its size is 0
Fixes #254
=> #254 empty repository causes runtime exception at `quantity-of-deliverables.rb`

judges/github-events/github-events.rb, test/judges/test-github-events.rb
=> #276: fix duplicated PullRequestReviewEvent events

judges/quality-of-service/quality-of-service.rb, judges/quality-of-service/simple-collect.yml, test/judges/test-quality-of-service.rb
@yegor256 merge https://github.com/zerocracy/fbe/pull/85  before
Closes #190
=> #190: calculate average review time for pr

judges/github-events/github-events.rb, test/judges/test-github-events.rb
=> #325: fix empty author id

judges/quality-of-service/quality-of-service.rb, judges/quality-of-service/simple-collect.yml, test/judges/test-quality-of-service.rb
=> #220: calculate average reviews per pr

judges/quality-of-service/quality-of-service.rb, judges/quality-of-service/simple-collect.yml, test/judges/test-quality-of-service.rb
=> #193: calculate average release hoc and commits size

judges/quantity-of-deliverables/count-all.yml, judges/quantity-of-deliverables/quantity-of-deliverables.rb, test/judges/test-quantity-of-deliverables.rb
=> #195: calculate total number of CI builds

Gemfile.lock, judges/dimensions-of-terrain/dimensions-of-terrain.rb, judges/dimensions-of-terrain/measure-all.yml, test/judges/test-dimensions-of-terrain.rb
@yegor256 please merge https://github.com/zerocracy/fbe/pull/103 before
Closes #201
=> #201 count `total_commits`

judges/dimensions-of-terrain/dimensions-of-terrain.rb, judges/dimensions-of-terrain/measure-all.yml, test/judges/test-dimensions-of-terrain.rb
=> 202: calculate total number of files

judges/dimensions-of-terrain/dimensions-of-terrain.rb, judges/dimensions-of-terrain/measure-all.yml, test/judges/test-dimensions-of-terrain.rb
=> #203: calculate total number of unique contributors

judges/quality-of-service/quality-of-service.rb, judges/quality-of-service/simple-collect.yml, test/judges/test-quality-of-service.rb
=> #227: calculate average triage time for issues

judges/github-events/github-events.rb, test/judges/test-github-events.rb
=> #373: fix fetch contributors if tag empty

test/judges/test-dimensions-of-terrain.rb
=> #372: add test cases for DoT

Gemfile.lock, judges/find-all-issues/find-all-issues.rb, judges/find-all-issues/scan-issues.yml, judges/find-all-issues/scan-with-existing-issue.yml, test/judges/test-find-all-issues.rb
=> #102: implement find-all-issues judge

judges/github-events/github-events.rb, test/judges/test-github-events.rb
=> #526 count the number of `review_comments`

judges/is-human-or-robot/is-human-or-robot.rb, test/judges/test-is-human-or-robot.rb
=> #510 handle missing github user

judges/add-review-comments/add-review-comments.rb, test/judges/test-add-review-comments.rb
=> #543 fix "repository not found" when trying to add review comments bug Something isn't working

judges/quality-of-service/quality-of-service.rb, test/judges/test-quality-of-service.rb
=> #595: fix fill up `since` property for quality-of-service facts

action.yml, entry-test.sh, entry.sh
=> take default GITHUB_TOKEN

action.yml, judges/find-all-issues/find-all-issues.rb, judges/find-all-issues/scan-issues.yml, judges/find-all-issues/scan-with-existing-issue.yml, test/judges/test-find-all-issues.rb
=> scan issues better

judges/assignee-was-attached/assignee-was-attached.rb, judges/assignee-was-attached/find-assignee.yml, test/judges/test-assignee-was-attached.rb, test/smart_factbase.rb, test/test__helper.rb
Test fail, because this https://github.com/zerocracy/fbe/pull/190 PR need merge before
Closes #659
=> #659: implement pull-was-merged judge

judges/quality-of-service/some_backlog_size.rb, judges/quality-of-service/some_build_success_rate.rb, judges/quality-of-service/some_issue_lifetime.rb, judges/quality-of-service/some_merged_pulls.rb, judges/quality-of-service/some_pull_hoc_size.rb, judges/quality-of-service/some_release_hoc_size.rb, judges/quality-of-service/some_release_interval.rb, judges/quality-of-service/some_review_time.rb, judges/quality-of-service/some_triage_time.rb, test/judges/test-quality-of-service.rb
=> #1043: fix analyze the interval between `fact.since` and `fact.when` for metrics in `quality-of-service` judge

judges/quality-of-service/quality-of-service.rb, judges/quality-of-service/simple-collect.yml, judges/quality-of-service/skip-duplicate-scan.yml, judges/quantity-of-deliverables/count-all.yml, judges/quantity-of-deliverables/quantity-of-deliverables.rb, test/judges/test-quality-of-service.rb, test/judges/test-quantity-of-deliverables.rb
=> #1044: fix creating and incrementing logic for `quality-of-service` and `quantity-of-deliverables` judges
